// ==UserScript==
// @name                WME Validator Localization for Venezuela
// @version             1.1.15
// @description         This script localizes WME Validator for Venezuela. You also need main package (WME Validator) installed.
// @match               https://editor-beta.waze.com/*editor/*
// @match               https://www.waze.com/*editor/*
// @grant               none
// @run-at              document-start
// ==/UserScript==
//
/*
  Please translate all the lines marked with "TODO: "
  Please DO NOT change ".en" properties. To override english text use "titleEN",
  "problemEN" and "solutionEN" properties (see an example below).

  See Settings->About->Available checks for complete list of checks and their params.

  Examples:

  Enable #170 "Lowercase street name" but allow lowercase "exit" and "to":
    "170.enabled": true,
    "170.params": {
        "regexp": "/^((exit|to) )?[a-z]/",
    "},

  Enable #130 "Custom check" to find a dot in street names, but allow dots at Ramps:
    "130.enabled": true,
    "130.params": {
        "titleEN": "Street name with a dot",
        "problemEN": "There is a dot in the street name (excluding Ramps)",
        "solutionEN": "Expand the abbreviation or remove the dot",
        "template": "${type}:${street}",
        "regexp": "D/^[^4][0-9]?:.*\\./",
    },
    *Note: use D at the beginning of RegExp to enable debugging on JS console.
    *Note: do not forget to escape backslashes in strings, i.e. use "\\" instead of "\".
*/

window.WME_Validator_Venezuela = {
  ".country": [
    "Venezuela",
    "Spain",
    "Andorra",
    "Bolivia",
    "Costa Rica",
    "Colombia",
    "Cuba",
    "Dominican Republic",
    "Ecuador",
    "Equatorial Guinea",
    "Guatemala",
    "Honduras",
    "Nicaragua",
    "Panama",
    "Peru",
    "Paraguay",
    "El Salvador",
    "Uruguay"
  ],
  ".codeISO": "VE",
  ".author": "robindlc and fernandoanguita and xanderb",
  ".updated": "2015-11-29",
  ".link": "TODO: ",
  ".lng": [
    "ES",
    "ES-419",
    "GL"
  ],
  "city.consider.en": "consider this city name:",
  "city.consider": "considerar este nombre de ciudad:",
  "city.1.en": "city name is too short",
  "city.1": "nombre de ciudad demasiado corto",
  "city.2.en": "expand the abbreviation",
  "city.2": "expandir la abreviación",
  "city.3.en": "complete short name",
  "city.3": "completar nombre corto",
  "city.4.en": "complete city name",
  "city.4": "completar nombre de ciudad",
  "city.5.en": "correct letter case",
  "city.5": "corregir mayúsculas",
  "city.6.en": "check word order",
  "city.6": "comprobar orden de palabras",
  "city.7.en": "check abbreviations",
  "city.7": "comprobar abreviaciones",
  "city.8a.en": "add county name",
  "city.8a": "añadir nombre de país",
  "city.8r.en": "remove county name",
  "city.8r": "eliminar nombre de país",
  "city.9.en": "check county name",
  "city.9": "comprobar nombre de país",
  "city.10a.en": "add a word",
  "city.10a": "añadir palabra",
  "city.10r.en": "remove a word",
  "city.10r": "eliminar palabra",
  "city.11.en": "add county code",
  "city.11": "añadir código de país",
  "city.12.en": "identical names, but different city IDs",
  "city.12": "nombres idénticos, pero ciudades con diferentes IDs",
  "city.13a.en": "add a space",
  "city.13a": "añadir espacio",
  "city.13r.en": "remove a space",
  "city.13r": "eliminar espacio",
  "city.14.en": "check the number",
  "city.14": "revisar el número",
  "props.skipped.title.en": "The segment is not checked",
  "props.skipped.title": "El segmento no está revisado",
  "props.skipped.problem.en": "The segment is modified after 2014-05-01 AND locked for you, so Validator did not check it",
  "props.skipped.problem": "El    segmento se modificó después del 01-05-2014 Y está bloqueado por ti, por lo que Validator no lo revisó",
  "err.regexp.en": "Error parsing option for check #${n}:",
  "err.regexp": "Error al analizar la opción de revisión #${n}:",
  "props.disabled.en": "WME Validator is disabled",
  "props.disabled": "WME Validator deshabilitado",
  "props.limit.title.en": "Too many issues reported",
  "props.limit.title": "Demasiados problemas notificados",
  "props.limit.problem.en": "There are too many issues reported, so some of them might not be shown",
  "props.limit.problem": "Hay demasiados problemas notificados, puede que no se muestren todos",
  "props.limit.solution.en": "Deselect the segment and stop scanning process. Then click red '✘' (Clear report) button",
  "props.limit.solution": "Deselecciona el segmento y detiene el proceso de escaneo. Luego pincha el botón con la '✘' roja (Limpiar Reporte)",
  "props.reports.en": "reports",
  "props.reports": "informes",
  "props.noneditable.en": "You cannot edit this segment",
  "props.noneditable": "No puedes editar este segmento",
  "report.save.en": "Save this report",
  "report.save": "Guardar este informe",
  "report.list.andUp.en": "and up",
  "report.list.andUp": "y subiendo",
  "report.list.severity.en": "Severity:",
  "report.list.severity": "Severidad:",
  "report.list.reportOnly.en": "only in report",
  "report.list.reportOnly": "sólo en el informe",
  "report.list.forEditors.en": "For editors level:",
  "report.list.forEditors": "Para editores nivel:",
  "report.list.forCountries.en": "For countries:",
  "report.list.forCountries": "Para paises:",
  "report.list.forStates.en": "For states:",
  "report.list.forStates": "Para estados:",
  "report.list.forCities.en": "For cities:",
  "report.list.forCities": "Para ciudades:",
  "report.list.params.en": "Params to configure in localization pack:",
  "report.list.params": "Parámetros para configurar en el paquete de localización:",
  "report.list.params.set.en": "Current configuration for ${country}:",
  "report.list.params.set": "Parámetros ajustados en el paquete de localización:",
  "report.list.enabled.en": "${n} checks are enabled for",
  "report.list.enabled": "${n} revisiones están habilitadas para",
  "report.list.disabled.en": "${n} checks are disabled for",
  "report.list.disabled": "${n} revisiones están deshabilitadas para",
  "report.list.total.en": "There are ${n} checks available",
  "report.list.total": "Hay ${n} revisiones disponibles",
  "report.list.title.en": "Complete List of Checks for",
  "report.list.title": "Lista Completa de Revisiones para",
  "report.list.see.en": "See",
  "report.list.see": "Ver",
  "report.list.checks.en": "Settings->About->Available checks",
  "report.list.checks": "Configuración>Acerca>Revisiones disponibles",
  "report.list.fallback.en": "Localization Fallback Rules:",
  "report.list.fallback": "Reglas de Localización de respaldo:",
  "report.and.en": "and",
  "report.and": "y",
  "report.segments.en": "Total number of segments checked:",
  "report.segments": "Número total de segmentos revisados:",
  "report.customs.en": "Custom checks matched (green/blue):",
  "report.customs": "Revisiones personalizadas combinadas (verde/azul):",
  "report.reported.en": "Reported",
  "report.reported": "Reportados",
  "report.errors.en": "errors",
  "report.errors": "errores",
  "report.warnings.en": "warnings",
  "report.warnings": "advertencias",
  "report.notes.en": "notes",
  "report.notes": "notas",
  "report.link.wiki.en": "wiki",
  "report.link.wiki": "TODO: wiki",
  "report.link.forum.en": "forum",
  "report.link.forum": "TODO: forum",
  "report.link.other.en": "link",
  "report.link.other": "TODO: link",
  "report.contents.en": "Contents:",
  "report.contents": "Contenidos:",
  "report.summary.en": "Summary",
  "report.summary": "Resumen",
  "report.title.en": "WME Validator Report",
  "report.title": "Informe de WME Validator",
  "report.share.en": "to Share",
  "report.share": "para Compartir",
  "report.generated.by.en": "generated by",
  "report.generated.by": "generado por",
  "report.generated.on.en": "on",
  "report.generated.on": "activo",
  "report.source.en": "Report source:",
  "report.source": "Fuente del informe:",
  "report.filter.duplicate.en": "duplicate segments",
  "report.filter.duplicate": "segmentos duplicados",
  "report.filter.streets.en": "Streets and Service Roads",
  "report.filter.streets": "Calles y Calles de Servicio",
  "report.filter.other.en": "Other drivable and Non-drivable",
  "report.filter.other": "Otros conducibles y no conducibles",
  "report.filter.noneditable.en": "non-editable segments",
  "report.filter.noneditable": "segmentos no-editables",
  "report.filter.notes.en": "notes",
  "report.filter.notes": "notas",
  "report.filter.title.en": "Filter:",
  "report.filter.title": "Filtro:",
  "report.filter.excluded.en": "are excluded from this report.",
  "report.filter.excluded": "están excluidos de este informe.",
  "report.search.updated.by.en": "updated by",
  "report.search.updated.by": "actualizado por",
  "report.search.updated.since.en": "updated since",
  "report.search.updated.since": "actualizado desde",
  "report.search.city.en": "from",
  "report.search.city": "desde",
  "report.search.reported.en": "reported as",
  "report.search.reported": "reportado como",
  "report.search.title.en": "Search:",
  "report.search.title": "Búsqueda:",
  "report.search.only.en": "only segments",
  "report.search.only": "sólo segmentos",
  "report.search.included.en": "are included into the report.",
  "report.search.included": "están incluídos en el informe.",
  "report.beta.warning.en": "WME Beta Warning!",
  "report.beta.warning": "¡Advertencia WME Beta!",
  "report.beta.text.en": "This report is generated in beta WME with beta permalinks.",
  "report.beta.text": "Este informe se genera en WME Beta con permalinks beta.",
  "report.beta.share.en": "Please do not share those permalinks!",
  "report.beta.share": "Por favor no comparta estos permalinks!",
  "report.size.warning.en": "<b>Warning!</b><br>The report is ${n} characters long so <b>it will not fit</b> into a single forum or private message.\n<br>Please add <b>more filters</b> to reduce the size of the report.",
  "report.size.warning": "<b>¡Advertencia!</b><br> El informe tiene ${n} caracteres, por lo que <b>no cabrá</b> en un mensaje de foro o privado.\n<br>Por favor agrega <b>más filtros</b> para reducir el tamaño del informe.",
  "report.note.limit.en": "* Note: there were too many issues reported, so some of them are not counted in the summary.",
  "report.note.limit": "* Nota: había demasiados problemas reportados, por lo que algunos de ellos no se incluyen en el resumen.",
  "report.forum.en": "To motivate further development please leave your comment on the",
  "report.forum": "Para motivar futuros desarrollos, por favor deje su mensaje en el",
  "report.forum.link.en": "Waze forum thread.",
  "report.forum.link": "TODO: Waze forum thread.",
  "report.thanks.en": "Thank you for using WME Validator!",
  "report.thanks": "Gracias por usar WME Validator!",
  "msg.limit.segments.en": "There are too many segments.\n\nClick 'Show report' to review the report, then\n",
  "msg.limit.segments": "Hay demasiados segmentos.\n\nPincha 'Mostrar informe' para revisar el informe, luego\n",
  "msg.limit.segments.continue.en": "click '▶' (Play) to continue.",
  "msg.limit.segments.continue": "pincha '▶' para continuar.",
  "msg.limit.segments.clear.en": "click '✘' (Clear) to clear the report.",
  "msg.limit.segments.clear": "pulsa '✘' para borrar el informe.",
  "msg.pan.text.en": "Pan around to validate the map",
  "msg.pan.text": "Desplaza el mapa para validarlo",
  "msg.zoomout.text.en": "Zoom out to start WME Validator",
  "msg.zoomout.text": "Aleja el zoom\tpara iniciar WME Validator",
  "msg.click.text.en": "Click '▶' (Play) to validate visible map area",
  "msg.click.text": "Pincha '▶' para validar el área visible del mapa",
  "msg.autopaused.en": "autopaused",
  "msg.autopaused": "autopausado",
  "msg.autopaused.text.en": "Auto paused! Click '▶' (Play) to continue.",
  "msg.autopaused.text": "¡Autopausado! Pincha '▶' para continuar.",
  "msg.autopaused.tip.en": "WME Validator automatically paused on map drag or window size change",
  "msg.autopaused.tip": "WME Validator automáticamente pausó al arrastrar el mapa o cambiar el tamaño de la ventana",
  "msg.finished.text.en": "Click <b>'Show report'</b> to review map issues",
  "msg.finished.text": "Pincha <b>'Mostrar informe'</b> para ver los problemas del mapa",
  "msg.finished.tip.en": "Click '✉' (Share) button to post report on a\nforum or in a private message",
  "msg.finished.tip": "Pincha el botón '✉' (Compartir) para publicar el informe en un \nforo o en un mensaje privado",
  "msg.noissues.text.en": "Finished! No issues found!",
  "msg.noissues.text": "¡Terminado! ¡No se encontraron problemas!",
  "msg.noissues.tip.en": "Try to uncheck some filter options or start WME Validator over another map area!",
  "msg.noissues.tip": "¡Trata de deseleccionar algunas opciones de filtro o inicia WME Validator sobre otra zona del mapa!",
  "msg.scanning.text.en": "Scanning! Finishing in ~ ${n} min",
  "msg.scanning.text": "¡Escaneando! Finalizando en ~ ${n} minutos",
  "msg.scanning.text.soon.en": "Scanning! Finishing in a minute!",
  "msg.scanning.text.soon": "¡Escaneando! ¡Finalizando en un minuto!",
  "msg.scanning.tip.en": "Click 'Pause' button to pause or '■' (Stop) to stop",
  "msg.scanning.tip": "Pincha el botón 'Pausa' para pausar o '■' para detener",
  "msg.starting.text.en": "Starting! Layers are off to scan faster!",
  "msg.starting.text": "¡Comenzando! ¡Las capas están desactivadas para escanear más rápido!",
  "msg.starting.tip.en": "Use 'Pause' button to pause or '■' button to stop",
  "msg.starting.tip": "Usa el botón 'Pausa' para pausar o el botón '■' para detener",
  "msg.paused.text.en": "On pause! Click '▶' (Play) button to continue.",
  "msg.paused.text": "¡En pausa! Pincha el botón '▶' para continuar.",
  "msg.paused.tip.en": "To view the report click 'Show report' button (if available)",
  "msg.paused.tip": "Para ver el informe pincha el botón 'Mostrar informe' (si está disponible)",
  "msg.continuing.text.en": "Continuing!",
  "msg.continuing.text": "¡Continuando!",
  "msg.continuing.tip.en": "WME Validator will continue from the location it was paused",
  "msg.continuing.tip": "WME Validator continuará desde la ubicación en que fue pausado",
  "msg.settings.text.en": "Click <b>'Back'</b> to return to main view",
  "msg.settings.text": "Pincha <b>'Atrás'</b> para retornar a la vista principal",
  "msg.settings.tip.en": "Click 'Reset defaults' button to reset all settings in one click!",
  "msg.settings.tip": "Pincha el botón 'Restaurar valores predeterminados' para resetear todos los parámetros en un clic!",
  "msg.reset.text.en": "All filter options and settings have been reset to their defaults",
  "msg.reset.text": "Todas las opciones de filtro y configuración han sido reseteadas a sus valores por defecto",
  "msg.reset.tip.en": "Click 'Back' button to return to main view",
  "msg.reset.tip": "Pincha el botón 'Atrás' para retornar a la vista principal",
  "msg.textarea.pack.en": "This is a Greasemonkey/Tampermonkey script. You can copy and paste the text below into a <b>new .user.js file</b><br>or <b>paste it directly</b> into the Greasemonkey/Tampermonkey",
  "msg.textarea.pack": "Por favor copia el texto abajo y luego pégalo en el nuevo archivo <b>.user.js</b>",
  "msg.textarea.en": "Please copy the text below and then paste it into your forum post or private message",
  "msg.textarea": "Por favor copia el texto abajo y luego pégalo en tu publicación del foro o mensaje privado",
  "noaccess.text.en": "<b>Sorry,</b><br>You cannot use WME Validator over here.<br>Please check <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>the forum thread</a><br>for more information.",
  "noaccess.text": "<b>Lo sentimos,</b><br> No puedes usar WME Validator\taquí.<br>Por favor revisa <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>el hilo del foro</a><br>para más información.",
  "noaccess.tip.en": "Please check the forum thread for more information!",
  "noaccess.tip": "Por favor revisa el hilo del foro para más información!",
  "tab.switch.tip.on.en": "Click to switch highlighting on (Alt+V)",
  "tab.switch.tip.on": "Pincha para activar el resaltado",
  "tab.switch.tip.off.en": "Click to switch highlighting off (Alt+V)",
  "tab.switch.tip.off": "Pincha para desactivar el resaltado",
  "tab.filter.text.en": "filter",
  "tab.filter.text": "filtro",
  "tab.filter.tip.en": "Options to filter the report and highlighted segments",
  "tab.filter.tip": "Opciones para filtrar el informe y los segmentos resaltados",
  "tab.search.text.en": "search",
  "tab.search.text": "buscar",
  "tab.search.tip.en": "Advanced filter options to include only specific segments",
  "tab.search.tip": "Opciones de filtro avanzadas para incluir sólo segmentos específicos",
  "tab.help.text.en": "help",
  "tab.help.text": "ayuda",
  "tab.help.tip.en": "Need help?",
  "tab.help.tip": "¿Necesitas ayuda?",
  "filter.noneditables.text.en": "Exclude <b>non-editable</b> segments",
  "filter.noneditables.text": "Excluir segmentos <b>no-editables</b>",
  "filter.noneditables.tip.en": "Do not report locked segments or\nsegments outside of your editable areas",
  "filter.noneditables.tip": "No reportar segmentos bloqueados o \nsegmentos fuera de su área de edición",
  "filter.duplicates.text.en": "Exclude <b>duplicate</b> segments",
  "filter.duplicates.text": "Excluir segmentos <b>duplicados</b>",
  "filter.duplicates.tip.en": "Do not show the same segment in different\nparts of report\n* Note: this option DOES NOT affect highlighting",
  "filter.duplicates.tip": "No mostrar el mismo segmento en diferentes \npartes del reporte\n* Nota: esta opción NO AFECTA el resaltado",
  "filter.streets.text.en": "Exclude <b>Streets and Service Roads</b>",
  "filter.streets.text": "Excluir <b>Calles y Vías de Servicio</b>",
  "filter.streets.tip.en": "Do not report Streets and Service Roads",
  "filter.streets.tip": "No reportar Calles y Vías de Servicio",
  "filter.other.text.en": "Exclude <b>Other drivable and Non-drivable</b>",
  "filter.other.text": "Excluir <b>otros conducibles y no-conducibles</b>",
  "filter.other.tip.en": "Do not report Dirt, Parking Lot, Private Roads\nand non-drivable segments",
  "filter.other.tip": "No reportar Caminos de Tierra, Vías de Estacionamiento y Caminos Privados\ny no-conducibles",
  "filter.notes.text.en": "Exclude <b>notes</b>",
  "filter.notes.text": "Excluir <b>notas</b>",
  "filter.notes.tip.en": "Report only warnings and errors",
  "filter.notes.tip": "Reportar sólo advertencias y errores",
  "search.youredits.text.en": "Include <b>only your edits</b>",
  "search.youredits.text": "Incluir <b>sólo tus ediciones</b>",
  "search.youredits.tip.en": "Include only segments edited by you",
  "search.youredits.tip": "Incluir sólo los segmentos editados por ti",
  "search.updatedby.text.en": "<b>Updated by*:</b>",
  "search.updatedby.text": "<b>Actualizado por:</b>",
  "search.updatedby.tip.en": "Include only segments updated by the specified editor\n* Note: this option is available for country managers only\nThis field supports:\n - lists: me, otherEditor\n - wildcards: world*\n - negation: !me, *\n* Note: you may use 'me' to match yourself",
  "search.updatedby.tip": "Incluir sólo segmentos actualizados por el editor especificado\nEste campo soporta:\n - listas: yo, OtrosEditores\n - comodines: palabra*\n - negación: !yo, *\n* Nota: puedes usar 'me' para indicarte a ti mismo",
  "search.updatedby.example.en": "Example: me",
  "search.updatedby.example": "Ejemplo: me",
  "search.updatedsince.text.en": "<b>Updated since:</b>",
  "search.updatedsince.text": "<b>Actualizado desde:</b>",
  "search.updatedsince.tip.en": "Include only segments edited since the date specified\nFirefox date format: YYYY-MM-DD",
  "search.updatedsince.tip": "Incluir sólo segmentos editados desde la fecha especificada formato de fecha\nFirefox: AAAA-MM-DD",
  "search.updatedsince.example.en": "YYYY-MM-DD",
  "search.updatedsince.example": "AAAA-MM-DD",
  "search.city.text.en": "<b>City name:</b>",
  "search.city.text": "<b>Nombre de ciudad:</b>",
  "search.city.tip.en": "Include only segments with specified city name\nThis field supports:\n - lists: Paris, Meudon\n - wildcards: Greater * Area\n - negation: !Paris, *",
  "search.city.tip": "Incluir sólo segmentos con el nombre de ciudad especificado\nEste campo soporta:\n - listas: Paris, Meudon\n - comodines: Área * Mayor\n - negación: !Paris, *",
  "search.city.example.en": "Example: !Paris, *",
  "search.city.example": "Ejemplo: !Paris, *",
  "search.checks.text.en": "<b>Reported as:</b>",
  "search.checks.text": "<b>Reportado como:</b>",
  "search.checks.tip.en": "Include only segments reported as specified\nThis field matches:\n - severities: errors\n - check names: New road\n - check IDs: 200\nThis field supports:\n - lists: 36, 37\n - wildcards: *roundabout*\n - negation: !unconfirmed*, *",
  "search.checks.tip": "Incluir sólo segmentos reportados como específicos\nEste campo empareja:\n - severidades: errores\n - revisar nombres: Calle nueva\n - revisar IDs: 40\nEste campo soporta:\n - listas: 36, 37\n - comodines: *rotonda*\n - negación: !giros suaves*, *",
  "search.checks.example.en": "Example: reverse*",
  "search.checks.example": "Ejemplo: inverso*",
  "help.text.en": "<b>Help Topics:</b><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=666476#p666476\">F.A.Q.</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488\">Ask your question on the forum</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=661300#p661185\">How to adjust Validator for your country</a><br><a target=\"_blank\" href=\"https://www.waze.com/forum/viewtopic.php?t=76488&p=663286#p663286\">About the \"Might be Incorrect City Name\"</a>",
  "help.text": " <b>Hilos de Ayuda:</b><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?f=819&t=76488&p=666476#p666476'>F.A.Q.</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488'>Consulta tu duda en el foro</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?f=819&t=76488&p=661300#p661185'>Como ajustar Validator para tu país</a><br><a target='_blank' href='https://www.waze.com/forum/viewtopic.php?f=819&t=76488&p=663286#p663286'>Acerca de 'Puede ser un nombre de Ciudad incorrecto'</a>",
  "help.tip.en": "Open in a new browser tab",
  "help.tip": "Abrir en una nueva pestaña del explorador",
  "button.scan.tip.en": "Start scanning current map area\n* Note: this might take few minutes",
  "button.scan.tip": "Comenzar escaneo del área del mapa actual \n* Nota: esto puede tomar unos minutos",
  "button.scan.tip.NA.en": "Zoom out to start scanning current map area",
  "button.scan.tip.NA": "Aleja el zoom para comenzar a escanear el área del mapa actual",
  "button.pause.tip.en": "Pause scanning",
  "button.pause.tip": "Pausar escaneo",
  "button.continue.tip.en": "Continue scanning the map area",
  "button.continue.tip": "Continuar escaneando el área del mapa",
  "button.stop.tip.en": "Stop scanning and return to the start position",
  "button.stop.tip": "Detener el escaneo y volver a la posición de inicio",
  "button.clear.tip.en": "Clear report and segment cache",
  "button.clear.tip": "Borrar informe y caché de segmentos",
  "button.clear.tip.red.en": "There are too many reported segments:\n 1. Click 'Show report' to generate the report.\n 2. Click this button to clear the report and start over.",
  "button.clear.tip.red": "Hay demasiados segmentos reportados:\n 1. Pincha 'Mostrar informe' para generar informe.\n 2. Pincha este botón para borrar el informe y comenzar de nuevo.",
  "button.report.text.en": "Show report",
  "button.report.text": "Mostrar informe",
  "button.report.tip.en": "Apply the filter and generate HTML report in a new tab",
  "button.report.tip": "Aplicar el filtro y generar informe HTML en una nueva pestaña",
  "button.BBreport.tip.en": "Share the report on Waze forum or in a private message",
  "button.BBreport.tip": "Compartir el informe en el foro Waze o en un mensaje privado",
  "button.settings.tip.en": "Configure settings",
  "button.settings.tip": "Configurar ajustes",
  "tab.custom.text.en": "custom",
  "tab.custom.text": "personalizado",
  "tab.custom.tip.en": "User-defined custom checks settings",
  "tab.custom.tip": "Ajustes de revisión personalizados definidos por el usuario",
  "tab.settings.text.en": "Settings",
  "tab.settings.text": "Ajustes",
  "tab.scanner.text.en": "scanner",
  "tab.scanner.text": "escanear",
  "tab.scanner.tip.en": "Map scanner settings",
  "tab.scanner.tip": "Ajustes de escaneo de mapa",
  "tab.about.text.en": "about</span>",
  "tab.about.text": "acerca de</span>",
  "tab.about.tip.en": "About WME Validator",
  "tab.about.tip": "Acerca de WME Validator",
  "scanner.sounds.text.en": "Enable sounds",
  "scanner.sounds.text": "Habilitar sonidos",
  "scanner.sounds.tip.en": "Bleeps and the bloops while scanning",
  "scanner.sounds.tip": "Pitidos y sonidos mientras escanea",
  "scanner.sounds.NA.en": "Your browser does not support AudioContext",
  "scanner.sounds.NA": "Su navegador no admite AudioContext",
  "scanner.highlight.text.en": "Highlight issues on the map",
  "scanner.highlight.text": "Resalta problemas en el mapa",
  "scanner.highlight.tip.en": "Highlight reported issues on the map",
  "scanner.highlight.tip": "Resalta problemas reportados en el mapa",
  "scanner.slow.text.en": "Enable \"slow\" checks",
  "scanner.slow.text": "Activa 'slow' verificaciones",
  "scanner.slow.tip.en": "Enables deep map analysis\n* Note: this option might slow down the scanning process",
  "scanner.slow.tip": "Activa análisis profundo del mapa\n* Nota: esta opción puede ralentizar el proceso de escaneo",
  "scanner.ext.text.en": "Report external highlights",
  "scanner.ext.text": "Informa de resaltados externos",
  "scanner.ext.tip.en": "Report segments highlighted by WME Toolbox or WME Color Highlights",
  "scanner.ext.tip": "Informa de segmentos resaltados por WME Toolbox o WME Color Highlights",
  "advanced.atbottom.text.en": "At the bottom",
  "advanced.atbottom.text": "TODO: At the bottom",
  "advanced.atbottom.tip.en": "Put WME Validator at the bottom of the page",
  "advanced.atbottom.tip": "TODO: Put WME Validator at the bottom of the page",
  "custom.template.text.en": "<a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>Custom template</a>",
  "custom.template.text": "Plantilla personalizada",
  "custom.template.tip.en": "User-defined custom check expandable template.\n\nYou may use the following expandable variables:\nAddress:\n  ${country}, ${state}, ${city}, ${street},\n  ${altCity[index or delimeter]}, ${altStreet[index or delimeter]}\nSegment properties:\n  ${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n  ${length}, ${ID}\nHelpers:\n  ${drivable}, ${roundabout}, ${hasHNs},\n  ${Uturn}, ${deadEnd}, ${softTurns},\n  ${deadEndA}, ${partialA},\n  ${deadEndB}, ${partialB}\nConnectivity:\n  ${segmentsA}, ${inA}, ${outA}, ${UturnA},\n  ${segmentsB}, ${inB}, ${outB}, ${UturnB}",
  "custom.template.tip": "Plantilla para comprobaciones definidas por el usuario.\n\nPuede usar las siguientes variables expandibles:\n${country}, ${state}, ${city}, ${street},\n${country}, ${state}, ${city}, ${street},\n${altCity[index or delimeter]} Example: ${altCity[0]},\n${altStreet[index or delimeter]} Example: ${altStreet[##]},\n${type}, ${typeRank}, ${toll}, ${direction}, ${elevation}, ${lock},\n${length}, ${ID}, ${roundabout}, ${hasHNs},\n${drivable}, ${softTurns}, ${Uturn}, ${deadEnd},\n${segmentsA}, ${inA}, ${outB}, ${UturnA},\n${segmentsB}, ${inB}, ${outB}, ${UturnB}",
  "custom.template.example.en": "Example: ${street}",
  "custom.template.example": "Ejemplo: ${street}",
  "custom.regexp.text.en": "Custom <a target='_blank' href='https://www.waze.com/forum/viewtopic.php?t=76488&p=749456#p749456'>RegExp</a>",
  "custom.regexp.text": "Personalizado <a target='_blank' href='https://developer.mozilla.org/docs/JavaScript/Guide/Regular_Expressions'>RegExp</a>",
  "custom.regexp.tip.en": "User-defined custom check regular expression to match the template.\n\nCase-insensitive match: /regexp/i\nNegation (do not match): !/regexp/\nLog debug information on console: D/regexp/",
  "custom.regexp.tip": "Expresión regular de comprobación personalizada definida por el usuario para que coincida con la plantilla.\n\nCase-insensitive match: /regexp/i\nNegation (do not match): !/regexp/\nLog debug information on console: D/regexp/",
  "custom.regexp.example.en": "Example: !/.+/",
  "custom.regexp.example": "Ejemplo: !/.+/",
  "about.tip.en": "Open link in a new tab",
  "about.tip": "Pincha 'actualizar' para abrir el hilo del foro en una pestaña nueva",
  "button.reset.text.en": "Reset defaults",
  "button.reset.text": "Restablecer predeterminados",
  "button.reset.tip.en": "Revert filter options and settings to their defaults",
  "button.reset.tip": "Revertir opciones de filtro y ajustes a sus valores predeterminados",
  "button.list.text.en": "Available checks...",
  "button.list.text": "Comprobaciones disponibles...",
  "button.list.tip.en": "Show a list of checks available in WME Validator",
  "button.list.tip": "Muestra una lista de las comprobaciones disponibles en WME Validator",
  "button.wizard.tip.en": "Create localization package",
  "button.wizard.tip": "Crear paquete de localización",
  "button.back.text.en": "Back",
  "button.back.text": "Atrás",
  "button.back.tip.en": "Close settings and return to main view",
  "button.back.tip": "Cerrar configuración y volver a la vista principal",
  "1.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
  "1.title.en": "WME Toolbox: Roundabout which may cause issues",
  "1.title": "WME Toolbox: Rotonda que puede causar problemas",
  "1.problem.en": "Junction IDs of the roundabout segments are not consecutive",
  "1.problem": "Los números de identificación de los puntos de unión de los segmentos de la rotonda no son consecutivos",
  "1.solution.en": "Redo the roundabout",
  "1.solution": "Rehacer la rotonda",
  "2.title.en": "WME Toolbox: Simple segment",
  "2.title": "WME Toolbox: Segmento Simple",
  "2.problem.en": "The segment has unneeded geometry nodes",
  "2.problem": "El segmento tiene nodos de geometría innecesarios",
  "2.solution.en": "Simplify segment geometry by hovering mouse pointer and pressing \"d\" key",
  "2.solution": "Simplifica la geometría del segmento pasando el puntero del ratón por encima y pulsando la tecla 'd'",
  "3.title.en": "WME Toolbox: Lvl 2 lock",
  "3.title": "WME Toolbox: Bloqueo nivel 2",
  "3.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "3.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
  "4.title.en": "WME Toolbox: Lvl 3 lock",
  "4.title": "WME Toolbox: Bloqueo nivel 3",
  "4.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "4.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
  "5.title.en": "WME Toolbox: Lvl 4 lock",
  "5.title": "WME Toolbox: Bloqueo nivel 4",
  "5.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "5.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
  "6.title.en": "WME Toolbox: Lvl 5 lock",
  "6.title": "WME Toolbox: Bloqueo nivel 5",
  "6.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "6.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
  "7.title.en": "WME Toolbox: Lvl 6 lock",
  "7.title": "WME Toolbox: Bloqueo nivel 6",
  "7.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "7.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
  "8.title.en": "WME Toolbox: House numbers",
  "8.title": "WME Toolbox: Numeros de casas",
  "8.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "8.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
  "9.title.en": "WME Toolbox: Segment with time restrictions",
  "9.title": "WME Toolbox: Segmento con restricciones de tiempo",
  "9.problem.en": "The segment is highlighted by WME Toolbox. It is not a problem",
  "9.problem": "El segmento está resaltado por WME Toolbox. No es un problema",
  "13.title.en": "WME Color Highlights: Editor lock",
  "13.title": "WME Colour Highlights: Bloqueo de editor",
  "13.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "13.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "14.title.en": "WME Color Highlights: Toll road / One way road",
  "14.title": "WME Colour Highlights: Peaje / Vía de sentido único",
  "14.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "14.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "15.title.en": "WME Color Highlights: Recently edited",
  "15.title": "WME Colour Highlights: Editado recientemente",
  "15.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "15.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "16.title.en": "WME Color Highlights: Road rank",
  "16.title": "WME Colour Highlights: Rango de vías",
  "16.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "16.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "17.title.en": "WME Color Highlights: No city",
  "17.title": "WME Colour Highlights: Sin ciudad",
  "17.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "17.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "18.title.en": "WME Color Highlights: Time restriction / Highlighted road type",
  "18.title": "WME Colour Highlights: Restricción horaria / Tipo de vía resaltado",
  "18.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "18.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "19.title.en": "WME Color Highlights: No name",
  "19.title": "WME Colour Highlights: Sin nombre",
  "19.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "19.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "20.title.en": "WME Color Highlights: Filter by city",
  "20.title": "WME Colour Highlights: Filtro por ciudad",
  "20.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "20.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "21.title.en": "WME Color Highlights: Filter by city (alt. city)",
  "21.title": "WME Colour Highlights: Filtro por ciudad (alt. ciudad)",
  "21.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "21.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "22.title.en": "WME Color Highlights: Filter by editor",
  "22.title": "WME Colour Highlights: Filtro por editor",
  "22.problem.en": "The segment is highlighted by WME Color Highlights. It is not a problem",
  "22.problem": "El segmento está resaltado por WME Colour Highlights. No es un problema",
  "23.title.en": "Unconfirmed road",
  "23.title": "Segmento no confirmado",
  "23.problem.en": "Each segment must minimally have the Country and State information",
  "23.problem": "Cada segmento debe tener al menos el nombre del país o estado",
  "23.solution.en": "Confirm the road by updating its details",
  "23.solution": "Confirma la vía actualizando sus detalles",
  "24.problemLink": "W:Corrigiendo_ciudades_\"manchadas\"",
  "24.title.en": "Might be incorrect city name (only available in the report)",
  "24.title": "Puede haber nombre incorrecto de ciudad (sólo disponible en el informe)",
  "24.problem.en": "The segment might have incorrect city name",
  "24.problem": "El segmento puede tener un nombre de ciudad incorrecto",
  "24.solution.en": "Consider suggested city name and use this form to rename the city",
  "24.solution": "Considera el nombre de ciudad sugerido y use este formulario para renombrar la ciudad",
  "25.title.en": "Unknown direction of drivable road",
  "25.title": "Dirección del segmento marcada como desconocida",
  "25.problem.en": "'Unknown' road direction will not prevent routing on the road",
  "25.problem": "La dirección del segmento 'Desconocida' no impedirá enrutar por la vía",
  "25.solution.en": "Set the road direction",
  "25.solution": "Fijar la dirección de la vía",
  "27.enabled": true,
  "27.problemLink": "W:Corrigiendo_ciudades_\"manchadas\"",
  "27.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
  "27.title.en": "City name on Railroad",
  "27.title": "Nombre de ciudad en vía férrea",
  "27.problem.en": "City name on the Railroad may cause a city smudge",
  "27.problem": "Poner nombres de ciudad en la vía férrea puede generar ciudades manchadas",
  "27.solution.en": "In the address properties check the 'None' box next to the city name and then click 'Apply'",
  "27.solution": "En las propiedades de dirección seleccione la casilla 'Ninguno' cerca del nombre de ciudad, haz clic en 'Aplicar'",
  "28.problemLink": "W:Puntos_de_Unión._Guía_de_estilo#Bifurcaciones_de_rampas",
  "28.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
  "28.title.en": "Street name on two-way Ramp",
  "28.title": "Nombre de calle en una rampa bidireccional",
  "28.problem.en": "If Ramp is unnamed, the name of a subsequent road will propagate backwards",
  "28.problem": "Si la rampa no tiene nombre, el nombre del segmento siguiente se propagará hacia atrás",
  "28.solution.en": "In the address properties check the 'None' box next to the street name and then click 'Apply'",
  "28.solution": "En la caja de propiedades de la dirección, marca la casilla 'Ninguno' en el nombre de la calle y haz clic en 'Aplicar'",
  "29.problemLink": "W:Crear_y_editar_rotondas#Creaci.C3.B3n_de_una_rotonda_a_partir_de_una_intersecci.C3.B3n",
  "29.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
  "29.title.en": "Street name on roundabout",
  "29.title": "Nombre de calle en rotonda",
  "29.problem.en": "In Waze, we do not name roundabout segments",
  "29.problem": "En Waze, no nombramos los segmentos de las rotondas",
  "29.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' and then add 'Junction' landmark to name the roundabout",
  "29.solution": "En la caja de propiedades de la dirección, marca la casilla 'Ninguno' en el nombre de la calle y haz clic en 'Aplicar' y después crea un punto de interés tipo 'intersección / intercambio' para nombrar la rotonda",
  "34.title.en": "Empty alternate street",
  "34.title": "Nombre de calle alternativo vacío",
  "34.problem.en": "Alternate street name is empty",
  "34.problem": "El nombre de calle alternativo está vacío",
  "34.solution.en": "Remove empty alternate street name",
  "34.solution": "Borrar el nombre alternativo de calle vacío",
  "35.title.en": "Unterminated drivable road",
  "35.title": "Segmento de vía sin terminar",
  "35.problem.en": "Waze will not route from the unterminated segment",
  "35.problem": "Waze no enrutará desde un segmento sin terminar",
  "35.solution.en": "Move the segment a bit so the terminating node will be added automatically",
  "35.solution": "Mover un poco el segmento para que el extremo sin terminar sea añadido automáticamente al punto de unión",
  "38.problemLink": "W:Restricciones_horarias#En_segmentos",
  "38.title.en": "Expired segment restriction (slow)",
  "38.title": "Restricción de segmento caducada (slow)",
  "38.problem.en": "The segment has an expired restriction",
  "38.problem": "El segmento tiene una restricción caducada",
  "38.solution.en": "Click 'Edit restrictions' and delete the expired restriction",
  "38.solution": "Hacer clic en 'Editar restricciones' y borrar la restricción caducada",
  "39.problemLink": "W:Restricciones_horarias#En_giros",
  "39.title.en": "Expired turn restriction (slow)",
  "39.title": "Restricción de giro caducada (slow)",
  "39.problem.en": "The segment has a turn with an expired restriction",
  "39.problem": "El segmento tiene un giro con una restricción caducada",
  "39.solution.en": "Click clock icon next to the yellow arrow and delete the expired restriction",
  "39.solution": "Hacer clic en el icono de reloj cerca de la flecha amarilla y borrar la restricción caducada",
  "41.title.en": "Node A: Reverse connectivity of drivable road",
  "41.title": "Conectividad inversa en punto de unión A del segmento",
  "41.problem.en": "There is a turn which goes against the directionality of the segment at node A",
  "41.problem": "Hay un giro que va contra la dirección del segmento en el punto de unión A del segmento",
  "41.solution.en": "Make the segment 'Two-way', restrict all the turns at node A and then make the segment 'One way (A→B)' again",
  "41.solution": "Hacer el segmento 'bidireccional', restringir todos los giros en el punto de unión A y luego hacer el segmento 'Unidireccional (A→B)' nuevamente",
  "42.title.en": "Node B: Reverse connectivity of drivable road",
  "42.title": "Conectividad inversa en punto de unión B del segmento",
  "42.problem.en": "There is a turn which goes against the directionality of the segment at node B",
  "42.problem": "Hay un giro que va contra la dirección del segmento en el punto de unión B del segmento",
  "42.solution.en": "Make the segment 'Two-way', restrict all the turns at node B and then make the segment 'One way (B→A)' again",
  "42.solution": "Hacer el segmento 'bidireccional', restringir todos los giros en el punto de unión B y luego hacer el segmento 'Unidireccional (B→A)' nuevamente",
  "43.solutionLink": "W:Guía_rápida_de_edición_de_mapas#Dividir_un_segmento",
  "43.title.en": "Self connectivity",
  "43.title": "Auto conectividad",
  "43.problem.en": "The segment is connected back to itself",
  "43.problem": "El segmento está conectado a si mismo",
  "43.solution.en": "Split the segment into THREE pieces",
  "43.solution": "Divide el segmento en TRES partes",
  "44.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
  "45.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
  "46.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
  "46.title.en": "Node A: No inward connectivity of drivable road (slow)",
  "46.title": "Sin entrada en A (slow)",
  "46.problem.en": "The drivable non-private segment has no single inward turn enabled at node A",
  "46.problem": "El segmento no-privado no tiene ningún giro de entrada habilitado en el punto de unión A",
  "46.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node A",
  "46.solution": "Selecciona un segmento adyacente y habilita al menos un giro hacia el segmento en el punto de unión A",
  "47.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
  "47.title.en": "Node B: No inward connectivity of drivable road (slow)",
  "47.title": "Sin entrada en B (slow)",
  "47.problem.en": "The drivable non-private segment has no single inward turn enabled at node B",
  "47.problem": "El segmento no-privado no tiene ningún giro de entrada habilitado en el punto de unión B",
  "47.solution.en": "Select an adjacent segment and enable at least one turn to the segment at node B",
  "47.solution": "Selecciona un segmento adyacente y habilita al menos un giro hacia el segmento en el punto de unión B",
  "48.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
  "48.title.en": "Two-way drivable roundabout segment",
  "48.title": "Segmento de rotonda bidireccional",
  "48.problem.en": "The drivable roundabout segment is bidirectional",
  "48.problem": "El segmento de rotonda es bidireccional",
  "48.solution.en": "Redo the roundabout",
  "48.solution": "Rehacer la rotonda",
  "50.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
  "57.enabled": true,
  "57.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
  "57.title.en": "City name on named Ramp",
  "57.title": "Nombre de ciudad en rampa con nombre",
  "57.problem.en": "City name on the named Ramp may affect search results",
  "57.problem": "Poner el nombre de ciudad en las rampas puede afectar a los resultados de búsqueda",
  "57.solution.en": "In the address properties check the 'None' box next to the city name and then click 'Apply'",
  "57.solution": "En las propiedades de dirección seleccione la casilla 'Ninguno' cerca del nombre de ciudad, haz clic en 'Aplicar'",
  "59.enabled": true,
  "59.problemLink": "W:Corrigiendo_ciudades_'manchadas'",
  "59.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
  "59.title.en": "City name on Freeway",
  "59.title": "Nombre de Ciudad en Autopista",
  "59.problem.en": "City name on the Freeway may cause a city smudge",
  "59.problem": "Poner nombres de ciudad en la Autopista puede generar ciudades manchadas",
  "59.solution.en": "In the address properties check the 'None' box next to the city name and then click 'Apply'",
  "59.solution": "En las propiedades de dirección seleccione la casilla 'Ninguno' cerca del nombre de ciudad, haz clic en 'Aplicar'",
  "73.enabled": true,
  "73.title.en": "Too short street name",
  "73.title": "Menos de 3 caracteres de longitud en el nombre de la calle",
  "73.problem.en": "The street name is less than ${n} letters long and it is not a highway",
  "73.problem": "El nombre de la calle tiene una longitud de menos de 3 caracteres",
  "73.solution.en": "Correct the street name",
  "73.solution": "Corrige el nombre de la calle",
  "74.problemLink": "W:Crear_y_editar_rotondas",
  "74.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
  "78.solutionLink": "W:Guía_rápida_de_edición_de_mapas#Dividir_un_segmento",
  "78.title.en": "Same endpoints drivable segments (slow)",
  "78.title": "Segmentos con los mismos puntos de inicio y final (slow)",
  "78.problem.en": "Two drivable segments share the same two endpoints",
  "78.problem": "Dos segmentos comparten los puntos de inicio y final",
  "78.solution.en": "Split the segment. You might also remove one of the segments if they are identical",
  "78.solution": "Divide el segmento. También puedes borrar uno de los segmentos si son idénticos",
  "87.problemLink": "W:Crear_y_editar_rotondas",
  "87.solutionLink": "W:Crear_y_editar_rotondas#Arreglar_rotondas_editadas_manualmente",
  "87.title.en": "Node A: Multiple outgoing segments at roundabout",
  "87.title": "Más de un segmento de salida en el punto de unión A de la rotonda",
  "87.problem.en": "The drivable roundabout node A has more than one outgoing segment connected",
  "87.problem": "La rotonda tiene en el punto de unión A más de un segmento de salida conectado",
  "87.solution.en": "Redo the roundabout",
  "87.solution": "Rehacer la rotonda",
  "90.enabled": true,
  "90.title.en": "Two-way Freeway segment",
  "90.title": "Segmento de Autopista bidireccional",
  "90.problem.en": "Most of the Freeways are split into two one-way roads, so this two-way segment might be a mistake",
  "90.problem": "La mayoría de las Autopistas están separadas en dos vías de un sentido, por lo que este segmento bidireccional puede ser un error",
  "90.solution.en": "Check Freeway direction",
  "90.solution": "Revisar dirección de Autopista",
  "99.title.en": "U-turn at roundabout entrance (slow)",
  "99.title": "Giro en U en la entrada de rotonda (slow)",
  "99.problem.en": "The roundabout entrance segment has a U-turn enabled",
  "99.problem": "El segmento de entrada a la rotonda tiene un giro en U habilitado",
  "99.solution.en": "Disable U-turn",
  "99.solution": "Deshabilitar el giro en U",
  "101.enabled": false,
  "101.title.en": "Closed road (only available in the report)",
  "101.title": "Zona en construcción (sólo disponible en el informe)",
  "101.problem.en": "The segment is marked as closed",
  "101.problem": "El segmento está marcado como zona de construcción",
  "101.solution.en": "If the construction is done, restore the segment connectivity and remove the suffix",
  "101.solution": "Si la construcción está terminada, volver a conectar el segmento y borrar el sufijo",
  "102.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
  "102.title.en": "Node A: No outward connectivity of drivable road (slow)",
  "102.title": "Sin salida en A (slow)",
  "102.problem.en": "The drivable segment has no single outward turn enabled at node A",
  "102.problem": "El segmento no tiene ningún giro de salida habilitado en el punto de unión A",
  "102.solution.en": "Enable at least one outward turn from the segment at node A",
  "102.solution": "Habilita al menos un giro de salida desde el segmento en el punto de unión A",
  "103.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Establecer_giros_permitidos_.28conexiones.29",
  "103.title.en": "Node B: No outward connectivity of drivable road (slow)",
  "103.title": "Sin salida en B (slow)",
  "103.problem.en": "The drivable segment has no single outward turn enabled at node B",
  "103.problem": "El segmento no tiene ningún giro de salida habilitado en el punto de unión B",
  "103.solution.en": "Enable at least one outward turn from the segment at node B",
  "103.solution": "Habilita al menos un giro de salida desde el segmento en el punto de unión B",
  "104.title.en": "Railroad used for comments",
  "104.title": "Vía férrea usada para comentarios",
  "104.problem.en": "The Railroad segment is probably used as a map comment",
  "104.problem": "El segmento de vía férrea es probablemente usado como comentario de mapa",
  "104.solution.en": "Remove the comment as Railroads will be added to the client display",
  "104.solution": "Borrar el comentario ya que las vías férreas serán añadidas al mapa del cliente",
  "107.title.en": "Node A: No connection (slow)",
  "107.title": "Sin conexión en punto de unión A (slow)",
  "107.problem.en": "The node A of the drivable segment is within 5m from another drivable segment but not connected by a junction",
  "107.problem": "El punto de unión A del segmento está a menos de 5 metros de otro segmento pero no está conectado",
  "107.solution.en": "Drag the node A to the nearby segment so that it touches or move it a bit further away",
  "107.solution": "Conectar el punto de unión A a un segmento cercano o separarlos un poco más",
  "108.title.en": "Node B: No connection (slow)",
  "108.title": "Sin conexión en punto de unión B (slow)",
  "108.problem.en": "The node B of the drivable segment is within 5m from another drivable segment but not connected by a junction",
  "108.problem": "El punto de unión B del segmento está a menos de 5 metros de otro segmento pero no está conectado",
  "108.solution.en": "Drag the node B to the nearby segment so that it touches or move it a bit further away",
  "108.solution": "Conectar el punto de unión B a un segmento cercano o separarlos un poco más",
  "109.solutionLink": "W:Guía_rápida_de_edición_de_mapas#Eliminar_un_punto_de_uni.C3.B3n",
  "109.title.en": "Too short segment",
  "109.title": "Segmento muy corto",
  "109.problem.en": "The drivable non-terminal segment is less than ${n}m long so it is hard to see it on the map and it can cause routing problems",
  "109.problem": "El segmento tiene menos de 2 metros de longitud, así que es difícil de ver en el mapa",
  "109.solution.en": "Increase the length, or remove the segment, or join it with one of the adjacent segments",
  "109.solution": "Aumentar la longitud, borrar el segmento, o unirlo a un segmento adyacente",
  "112.title.en": "Too long Ramp name",
  "112.title": "Más de 55 caracteres en el nombre de la Rampa",
  "112.problem.en": "The Ramp name is more than ${n} letters long",
  "112.problem": "El nombre de la Rampa tiene más de 55 caracteres",
  "112.solution.en": "Shorten the Ramp name",
  "112.solution": "Acorta el nombre de la Rampa",
  "114.enabled": false,
  "114.title.en": "Node A: Non-drivable connected to drivable (slow)",
  "114.title": "No transitable conectada a transitable en el punto de unión A (slow)",
  "114.problem.en": "The non-drivable segment makes a junction with a drivable at node A",
  "114.problem": "El segmento no transitable tiene un punto de unión con un segmento transitable en el extremo A",
  "114.solution.en": "Disconnect node A from all of the drivable segments",
  "114.solution": "Desconecta el extremo A de todos los segmentos transitables",
  "115.enabled": false,
  "115.title.en": "Node B: Non-drivable connected to drivable (slow)",
  "115.title": "No transitable conectada a transitable en el punto de unión B (slow)",
  "115.problem.en": "The non-drivable segment makes a junction with a drivable at node B",
  "115.problem": "El segmento no transitable tiene un punto de unión con un segmento transitable en el extremo B",
  "115.solution.en": "Disconnect node B from all of the drivable segments",
  "115.solution": "Desconecta el extremo B de todos los segmentos transitables",
  "116.title.en": "Out of range elevation",
  "116.title": "Elevación fuera de rango",
  "116.problem.en": "The segment elevation is out of range",
  "116.problem": "La elevación del segmento está fuera de rango",
  "116.solution.en": "Correct the elevation",
  "116.solution": "Corrige la elevación",
  "117.enabled": false,
  "117.title.en": "Obsolete CONST ZN marker",
  "117.title": "Marcado obsoleto: CONST ZN",
  "117.problem.en": "The segment is marked with obsolete CONST ZN suffix",
  "117.problem": "El segmento está marcado con el sufijo obsoleto CONST ZN",
  "117.solution.en": "Change CONST ZN to (closed)",
  "117.solution": "Cambiar CONST ZN a (closed)",
  "118.title.en": "Node A: Overlapping segments (slow)",
  "118.title": "Segmentos superpuestos en A (slow)",
  "118.problem.en": "The segment is overlapping with the adjacent segment at node A",
  "118.problem": "El segmento se solapa con el segmento adyacente en el punto de unión A",
  "118.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node A",
  "118.solution": "Separa los dos segmentos al menos 2º o elimina el nodo de geometría innecesario o borra el segmento duplicado en el punto de unión A",
  "119.title.en": "Node B: Overlapping segments (slow)",
  "119.title": "Segmentos superpuestos en B (slow)",
  "119.problem.en": "The segment is overlapping with the adjacent segment at node B",
  "119.problem": "El segmento se solapa con el segmento adyacente en el punto de unión B",
  "119.solution.en": "Spread the segments at 2° or delete unneeded geometry point or delete the duplicate segment at node B",
  "119.solution": "Separa los dos segmentos al menos 2º o elimina el nodo de geometría innecesario o borra el segmento duplicado en el punto de unión B",
  "120.title.en": "Node A: Too sharp turn (slow)",
  "120.title": "Giro demasiado cerrado en A (slow)",
  "120.problem.en": "The drivable segment has a very acute turn at node A",
  "120.problem": "El segmento tiene un giro demasiado cerrado en el punto de unión A",
  "120.solution.en": "Disable the sharp turn at node A or spread the segments at 30°",
  "120.solution": "Desactiva el giro cerrado en el punto de unión A o considera separar los segmentos hasta un ángulo de 30°",
  "121.title.en": "Node B: Too sharp turn (slow)",
  "121.title": "Giro demasiado cerrado en B (slow)",
  "121.problem.en": "The drivable segment has a very acute turn at node B",
  "121.problem": "El segmento tiene un giro demasiado cerrado en el punto de unión B",
  "121.solution.en": "Disable the sharp turn at node B or spread the segments at 30°",
  "121.solution": "Desactiva el giro cerrado en el punto de unión B o considera separar los segmentos hasta un ángulo de 30°",
  "128.title.en": "User-defined custom check (green)",
  "128.title": "Comprobación personalizada por el usuario 1",
  "128.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
  "128.problem": "Alguna de las propiedades del segmento coinciden con la expresión regular definida por el usuario (ver Ajustes→Personalización)",
  "128.solution.en": "Solve the issue",
  "128.solution": "Resolver el problema",
  "129.title.en": "User-defined custom check (blue)",
  "129.title": "Comprobación personalizada por el usuario 2",
  "129.problem.en": "Some of the segment properties matched against the user-defined regular expression (see Settings→Custom)",
  "129.problem": "Alguna de las propiedades del segmento coinciden con la expresión regular definida por el usuario (ver Ajustes→Personalización)",
  "129.solution.en": "Solve the issue",
  "129.solution": "Resolver el problema",
  "130.enabled": true,
  "130.severity": "N",
  "130.params": {
    "titleEN": "No lock on Freeway",
    "problemEN": "The Freeway segment should be locked to Lvl 4",
    "solutionEN": "Lock the segment",
    "template": "${type}:${lock}",
    "regexp": "/^3:[^456]/"
  },
  "130.problemLink": "W:Venezuela/MMR_2015#Tipos_de_v.C3.ADas",
  "130.title.en": "Custom check",
  "130.title": "Nivel de bloqueo de Autopista urbana incorrecto",
  "130.problem.en": "The segment matched custom conditions",
  "130.problem": "El segmento de Autopista no está bloqueado a nivel 4",
  "130.solution.en": "Solve the issue",
  "130.solution": "Bloquear el segmento de Autopista a nivel 4",
  "131.enabled": true,
  "131.severity": "N",
  "131.params": {
    "titleEN": "No lock on Major Highway",
    "problemEN": "The Major Highway segment should be locked to Lvl 5",
    "solutionEN": "Lock the segment",
    "template": "${type}:${lock}:${street}",
    "regexp": "/^6:[5-6]:N-/"
  },
  "131.problemLink": "W:Venezuela/MMR_2015#Tipos_de_v.C3.ADas",
  "131.title.en": "No lock on Major Highway",
  "131.title": "Nivel de bloqueo de Carretera Primaria urbana incorrecto",
  "131.problem.en": "Urban Major Highways should be locked at 5",
  "131.problem": "El segmento de  Carretera Primaria urbana no está bloqueado a nivel 5",
  "131.solution.en": "Lock the segment",
  "131.solution": "Bloquear el segmento de Carretera Primaria urbana a nivel 5",
  "133.enabled": true,
  "133.severity": "N",
  "133.params": {
    "titleEN": "No lock on Ramp",
    "problemEN": "The Ramp segment should be locked to Lvl 3",
    "solutionEN": "Lock the segment",
    "template": "${type}:${lock}",
    "regexp": "/^4:[3-6]/"
  },
  "133.problemLink": "W:Dudas_frecuentes_editando_mapas#.C2.BFDebo_.22bloquear.22_mis_ediciones.3F",
  "133.title.en": "Custom check",
  "133.title": "No lock on Ramp",
  "133.problem.en": "The segment matched custom conditions",
  "133.problem": "The Ramp segment should be locked to Lvl 3",
  "133.solution.en": "Solve the issue",
  "133.solution": "Lock the segment",
  "150.title.en": "No lock on Freeway",
  "150.title": "Nivel de bloqueo de Autopista incorrecto",
  "150.problem.en": "The Freeway segment should be locked at least to Lvl ${n}",
  "150.problem": "El segmento de Autopista no está bloqueado a nivel ${n}",
  "150.solution.en": "Lock the segment",
  "150.solution": "Bloquear el segmento de Autopista a nivel ${n}",
  "150.params": {
  // {number} minimum lock level
  "n": 5,
  },
  "151.title.en": "No lock on Major Highway",
  "151.title": "Nivel de bloqueo de Carretera Primaria incorrecto",
  "151.problem.en": "The Major Highway segment should be locked at least to Lvl ${n}",
  "151.problem": "El segmento de Carretera Primaria no está bloqueado a nivel ${n}",
  "151.solution.en": "Lock the segment",
  "151.solution": "Bloquear el segmento de Carretera Primaria a nivel ${n}",
  "151.params": {
  // {number} minimum lock level
  "n": 4,
  },
  "169.title.en": "Incorrectly named street",
  "169.title": "Calle nombrada incorrectamente",
  "169.problem.en": "The street named incorrectly, illegal chars or words used",
  "169.problem": "La calle tiene el nombre incorrecto, usando caracteres o palabras ilegales",
  "169.solution.en": "Rename the segment in accordance with the guidelines",
  "169.solution": "Renombre la calle de acuerdo a los criterios establecidos",
  "170.enabled": true,
  "170.title.en": "Lowercase street name",
  "170.title": "Nombre de calle comienza con minúscula",
  "170.problem.en": "The street name starts with a lowercase word",
  "170.problem": "El nombre de la calle comienza con minúscula",
  "170.solution.en": "Correct lettercase in the street name",
  "170.solution": "Escribir en mayúscula la primera letra del nombre",
  "172.title.en": "Unneeded spaces in street name",
  "172.title": "Nombre de calle con espacios innecesarios",
  "172.problem.en": "Leading/trailing/double space in the street name",
  "172.problem": "Espacio en blanco inicial/final o doble en el nombre de la calle",
  "172.solution.en": "Remove unneeded spaces from the street name",
  "172.solution": "Borrar los espacios innecesarios del nombre de Calle",
  "173.enabled": false,
  "173.title.en": "No space before/after street abbreviation",
  "173.title": "Nombre de segmento sin espacio antes o después de una abreviación",
  "173.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the street name",
  "173.problem": "Sin espacio antes ('1943r.') o después ('St.Jan') de una abreviación en el nombre del segmento",
  "173.solution.en": "Add a space before/after the abbreviation",
  "173.solution": "Agregar un espacio antes/después de la abreviación",
  "175.solutionLink": "W:Crear_y_editar_segmentos_de_vías#Address_Properties",
  "175.title.en": "Empty street name",
  "175.title": "Nombre del segmento sólo con espacios",
  "175.problem.en": "The street name has only space characters or a dot",
  "175.problem": "El nombre del segmento sólo tiene espacios en blanco en el nombre",
  "175.solution.en": "In the address properties check the 'None' box next to the street name, click 'Apply' OR set a proper street name",
  "175.solution": "En la caja de propiedades de la dirección, marca la casilla 'Ninguno' en el nombre de la calle y haz clic en 'Aplicar' o escribe un nombre de calle correcto",
  "190.title.en": "Lowercase city name",
  "190.title": "Nombre de ciudad con minúscula",
  "190.problem.en": "The city name starts with a lowercase letter",
  "190.problem": "El nombre de la ciudad comienza con minúscula",
  "190.solution.en": "Use this form to rename the city",
  "190.solution": "Utiliza este formulario para renombrar la ciudad",
  "192.title.en": "Unneeded spaces in city name",
  "192.title": "Nombre de Ciudad con espacios innecesarios",
  "192.problem.en": "Leading/trailing/double space in the city name",
  "192.problem": "Espacio en blanco inicial/final o doble en el nombre de la ciudad",
  "192.solution.en": "Use this form to rename the city",
  "192.solution": "Use este formulario para renombrar la Ciudad",
  "193.enabled": false,
  "193.title.en": "No space before/after city abbreviation",
  "193.title": "Nombre de Ciudad sin espacio delante o atrás de una abreviación",
  "193.problem.en": "No space before ('1943r.') or after ('st.Jan') an abbreviation in the city name",
  "193.problem": "Sin espacio antes ('1943r.') o después ('St.Jean') de una abreviación en el nombre de la ciudad",
  "193.solution.en": "Use this form to rename the city",
  "193.solution": "Use este formulario para renombrar la Ciudad",
  "200.problemLink": "W:Giros_implícitos_y_explícitos",
  "200.solutionLink": "W:Giros_implícitos_y_explícitos#Mejores_pr.C3.A1cticas",
  "200.title.en": "Node A: Unconfirmed turn on minor road",
  "200.title": "Unión A: Giro suave (implícito) en segmento",
  "200.problem.en": "The minor drivable segment has an unconfirmed (soft) turn at node A",
  "200.problem": "El segmento tiene un giro no confirmado",
  "200.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
  "200.solution": "Haz clic en el giro indicado con un signo de interrogación color púrpura para confirmarlo. Nota: es posible que debas hacer el segmento bidireccional para ver todos los giros",
  "201.problemLink": "W:Giros_implícitos_y_explícitos",
  "201.solutionLink": "W:Giros_implícitos_y_explícitos#Mejores_pr.C3.A1cticas",
  "201.title.en": "Node A: Unconfirmed turn on primary road",
  "201.title": "Unión A: Giro suave (implícito) en segmento principal",
  "201.problem.en": "The primary segment has an unconfirmed (soft) turn at node A",
  "201.problem": "El segmento principal tiene un giro no confirmado",
  "201.solution.en": "Click the turn indicated with a purple question mark to confirm it. Note: you may need to make the segment 'Two-way' in order to see those turns",
  "201.solution": "Haz clic en el giro indicado con un signo de interrogación color púrpura para confirmarlo. Nota: es posible que debas hacer el segmento bidireccional para ver todos los giros"
};

// Dependant package:
window.WME_Validator_Mexico = {
  ".country": "Mexico",
  ".codeISO": "MX",
  ".author": "xanderb",
  ".updated": "2015-11-19",
  ".link": "TODO: ",
  ".fallbackCode": "ES"
};

// Dependant package:
window.WME_Validator_Chile = {
  ".country": "Chile",
  ".codeISO": "CL",
  ".author": "xanderb",
  ".updated": "2015-11-19",
  ".link": "TODO: ",
  ".fallbackCode": "ES",
  "59.enabled": true,
  "150.enabled": true,
  "170.enabled": true,
  "200.enabled": false
};

// Dependant package:
window.WME_Validator_Argentina = {
  ".country": "Argentina",
  ".codeISO": "AR",
  ".author": "xanderb",
  ".updated": "2015-11-19",
  ".link": "TODO: ",
  ".fallbackCode": "ES",
  "150.enabled": true,
  "169.enabled": true,
  "169.params": {
    "regexp": "/(^|\\b)[Cc]alle(?! [0-9]+( ([A-Z]|bis))?$)/"
  },
  "169.solutionLink": "W:Como_categorizar_y_nombrar_calles_(Argentina)#Calles"
};

